### PR TITLE
GameOver

### PR DESCRIPTION
**Pull request by solvim**
You died message instead of destroying player object when player gets caught

### CODE REVIEW

**Comment by solvim** [comment]
[End game (Die/win)](https://trello.com/c/oesqhdfj/88-end-game-die-win)

**Review by dadisigursveinn — COMMENTED** [review]
possibly just me being dumb but I cant figure out how to get the canvas to appear.

**Comment by hallur** [comment]
Nothing happens when the monster catches the player
end-game-bug

**Review by dadisigursveinn — APPROVED** [review]
Was able to get it to work, however the player can still move around after he "dies"

**Pull request merged**
